# Generated by Django 3.2.8 on 2021-11-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='source',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='source',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
    ]
